language: cpp

sudo: required

matrix:
  include:
    - env: CONFIG=Debug CXX=g++-5 FLAGS="-m32"
      compiler: gcc
    - env: CONFIG=Release CXX=g++-5 FLAGS="-m32"
      compiler: gcc
    - env: CONFIG=Debug CXX=g++-5 FLAGS="-m64"
      compiler: gcc
    - env: CONFIG=Release CXX=g++-5 FLAGS="-m64"
      compiler: gcc
    - env: CONFIG=Debug CXX=clang++ FLAGS="-m32"
      compiler: clang
    - env: CONFIG=Release CXX=clang++ FLAGS="-m32"
      compiler: clang
    - env: CONFIG=Debug CXX=clang++ FLAGS="-m64"
      compiler: clang
    - env: CONFIG=Release CXX=clang++ FLAGS="-m64"
      compiler: clang

before_script:
- sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y g++-5 g++-multilib lib32stdc++6
- cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_CXX_FLAGS=$FLAGS

script:
- make -C build

after_success:
- ./build/Any
- ./build/CommandLine -O3 -o output input1 input2 input3
- ./build/ExceptionWrapper
- ./build/Range
- ./build/String
- ./build/System
- ./build/X86Feature
