language: cpp

sudo: required

matrix:
  include:
    - env: CONFIG=debug FLAGS="-m32"
      compiler: gcc
    - env: CONFIG=release FLAGS="-m32"
      compiler: gcc
    - env: CONFIG=debug FLAGS="-m64"
      compiler: gcc
    - env: CONFIG=release FLAGS="-m64"
      compiler: gcc
    - env: CONFIG=debug FLAGS="-m32"
      compiler: clang
    - env: CONFIG=release FLAGS="-m32"
      compiler: clang
    - env: CONFIG=debug FLAGS="-m64"
      compiler: clang
    - env: CONFIG=release FLAGS="-m64"
      compiler: clang

before_script:
- sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y g++-multilib lib32stdc++6 libc6-dev-i386
- cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_CXX_FLAGS=$FLAGS

script:
- make -C build

after_success:
- ./build/Any
- ./build/CommandLine
- ./build/ExceptionWrapper
- ./build/String
- ./build/X86Feature
