language: cpp

sudo: required

matrix:
  include:
    - env: EVAL="CXX=g++-5" FLAGS="-m32" CONFIG=Debug
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5-multilib', 'lib32stdc++6', 'linux-libc-dev']
    - env: EVAL="CXX=g++-5" FLAGS="-m32" CONFIG=Release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5-multilib', 'lib32stdc++6', 'linux-libc-dev']
    - env: EVAL="CXX=g++-5" FLAGS="-m64" CONFIG=Debug
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
    - env: EVAL="CXX=g++-5" FLAGS="-m64" CONFIG=Release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
    - env: EVAL="CXX=clang++" FLAGS="-m32" CONFIG=Debug
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5-multilib', 'lib32stdc++6', 'linux-libc-dev']
    - env: EVAL="CXX=clang++" FLAGS="-m32" CONFIG=Release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5-multilib', 'lib32stdc++6', 'linux-libc-dev']
    - env: EVAL="CXX=clang++" FLAGS="-m64" CONFIG=Debug
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
    - env: EVAL="CXX=clang++" FLAGS="-m64" CONFIG=Release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

before_script:
- sudo ln -s /usr/include/asm-generic /usr/include/asm
- eval "${EVAL}"
- $CXX -v
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS=$FLAGS -DCMAKE_BUILD_TYPE=$CONFIG

script:
- make -C build

after_success:
- ./build/Any
- ./build/CommandLine -O3 -o output input1 input2 input3
- ./build/ExceptionWrapper
- ./build/Range
- ./build/String
- ./build/System
- ./build/X86Feature
