os: Visual Studio 2017
version: 0.0.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_VERSION: 15 2017
    VS_PLATFORM: win32
  - VS_VERSION: 15 2017
    VS_PLATFORM: x64

before_build:
- cmake -H. -Bbuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build/Corecat.sln
  parallel: true
  verbosity: minimal

test_script:
- build\%CONFIGURATION%\Any.exe
- build\%CONFIGURATION%\Benchmark.exe
- build\%CONFIGURATION%\CommandLine.exe -O3 -o output input1 input2 input3
- build\%CONFIGURATION%\ExceptionPtr.exe
- build\%CONFIGURATION%\Process.exe build\%CONFIGURATION%\Environment.exe
- build\%CONFIGURATION%\Range.exe
- build\%CONFIGURATION%\String.exe
- build\%CONFIGURATION%\System.exe
- build\%CONFIGURATION%\X86Feature.exe
